export const background = {
  splash: require('../assets/images/splash.png'),
  durotan: require('../assets/images/durotan.png'),
  girl: require('../assets/images/girl.png'),
  couple: require('../assets/images/couple.png'),
  female_profile: require('../assets/images/female_profile.png'),
  male_profile: require('../assets/images/male_profile.png'),
  place_holder: require('../assets/images/place_holder.png'),
  profile: require('../assets/images/profile.png'),
};

export const icons = {
  bullet: require('../assets/icons/bullet.png'),
  movies: require('../assets/icons/movies.png'),
  movies_outline: require('../assets/icons/movies_outline.png'),
  tv: require('../assets/icons/tv.png'),
  tv_outline: require('../assets/icons/tv_outline.png'),
  rating_star: require('../assets/icons/star.png'),
  youtube: require('../assets/icons/youtube.png'),
  search: require('../assets/icons/search.png'),
  twitter: require('../assets/icons/twitter.png'),
  facebook: require('../assets/icons/facebook.png'),
  instagram: require('../assets/icons/instagram.png'),
  profile: require('../assets/icons/profile.png'),
  profile_outline: require('../assets/icons/profile_outline.png'),
  settings: require('../assets/icons/settings.png'),
  close: require('../assets/icons/close.png'),
  bookmark: require('../assets/icons/bookmark.png'),
  bookmark_checked: require('../assets/icons/bookmark_checked.png'),
  logo: require('../assets/icons/logo.png'),
  zoom: require('../assets/icons/zoom.png'),
  tick: require('../assets/icons/tick.png'),
  share: require('../assets/icons/share.png'),
  comment: require('../assets/icons/comment.png'),
  like: require('../assets/icons/like.png'),
  like_checked: require('../assets/icons/like_checked.png'),
  favorite: require('../assets/icons/favorite.png'),
  favorite_checked: require('../assets/icons/favorite_checked.png'),
  netflix: require('../assets/icons/netflix.png'),
  disney_plus: require('../assets/icons/disney_plus.png'),
};

export default {background, icons};
